<a href="https://colab.research.google.com/github/karanidenis/alu-machine_learning/blob/main/Intro_to_ml_group_2_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Optimization Techniques in Machine Learning

Objective: This assignment aims to explore implementation or Machine Learning Models with regularization, optimization and Error analysis  techniques used in machine learning to improve models' performance, convergence speed, and efficiency..




**Instructions**

1. Acquire a publicly available dataset suitable for **classification** tasks.
2. Implement a simple machine learning model based on neural networks on the chosen dataset without any optimization techniques.
3. Implement and compare the model's performance after applying regularization and optimization techniques.
4. Compare and contrast L1 regularization (Lasso) and L2 regularization (Ridge). Discuss situations where each type of regularization might be preferred.
5. Make predictions using test data (Make sure you have training, validation, and test datasets)
6. Submit the code and a detailed explanation of the implementation, including libraries used, parameter settings, and observed results.




# **PRJECT NAME: SMART FASHION**

---

## Group Members and Roles:

1. **Denis Waweru**
   - Role: [Analyzer]
   - Responsibilities:

    *Implemented a prediction function for the models.

    *Generated basic confusion matrices.

    *Computed F1 scores for both models.

    *Conducted simple error analysis.


2. **Christian Makuochukwu Okeke**
   - Role: [Evaluator]
   - Responsibilities:
   
    *Trained models using appropriate techniques.

    *Evaluated model performance using accuracy and loss metrics.

    *Conducted basic analysis of results.

    *Provided clear explanations of the model's components.


3. **Praise Orly Atadja**
   - Role: [Project Coordinator]
   - Responsibilities:
    
    *Coordinated and scheduled team meetings.

    *Ensured that project timelines were met.

    *Facilitated communication among team members.

    *Developed the model structure and documentation.

  
4. **Jean Robert Gatwaza**
   - Role: [Role]
   - Responsibilities:

---



# Case Study and Implementation





# Case Study and Implementation

Case Study Summary: Fashion MNIST Classification

- The case study centers on implementing a neural network model for Fashion MNIST classification, initially devoid of optimization techniques.
- Key steps involve data handling through TensorFlow and Keras, encompassing loading, preprocessing, and splitting into training, validation, and test sets.
- A basic neural network architecture is established, featuring a flattened input, hidden layers with suitable activation functions, and a softmax activation for classification.
- To enhance model performance, regularization and optimization techniques are applied, including L1 and L2 regularization, dropout layers, batch normalization, and gradient clipping.
- A comprehensive comparative analysis assesses the impact of these techniques, with a particular focus on scenarios favoring L1 or L2 regularization.
- Evaluation involves making predictions using the test dataset, and the implementation code in Google Colabs is shared along with a README file detailing dataset sources, execution instructions, and a concise summary of observed results.

>Link to README file:
https://docs.google.com/document/d/1J0FS4AylwxgygREV6Rcu5F3ejN_IDSyMol1VitooHSY/edit?usp=sharing

In [1]:
#Import Necessary Libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Dropout, MaxPooling2D
from IPython.display import SVG
from tensorflow.keras.utils import model_to_dot, plot_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.regularizers import l1, l2
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly import tools
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from sklearn.metrics import confusion_matrix, classification_report

# The Dataset
**Short Description of the Data:**

The dataset comprises grayscale images of fashion items, each measuring 28x28 pixels for a total of 784 pixels. Each pixel has a single integer value between 0 and 255, representing its lightness or darkness. The dataset consists of 785 columns, with the first column containing class labels indicating the type of clothing, and the remaining columns containing pixel values. The task is to develop a model that can learn and generalize from this pixel data to accurately classify unseen fashion images into predefined categories.


Link to Dataset Source :

https://www.kaggle.com/datasets/zalando-research/fashionmnist


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [27]:
#TO DO: Load Data (Seprate into: Train, Validation and test sets)
IMG_ROWS = 28
IMG_COLS = 28
NUM_CLASSES = 10
TEST_SIZE = 0.2
RANDOM_STATE = 2018
NO_EPOCHS = 50
BATCH_SIZE = 128

train_file = "/content/drive/MyDrive/Colab Notebooks/fashion-mnist_train.csv"
test_file = "/content/drive/MyDrive/Colab Notebooks/fashion-mnist_test.csv"

train_data = pd.read_csv(train_file)
test_data = pd.read_csv(test_file)

print("Fashion MNIST train -  rows:",train_data.shape[0]," columns:", train_data.shape[1])
print("Fashion MNIST test -  rows:",test_data.shape[0]," columns:", test_data.shape[1])
print(test_data.shape)

Fashion MNIST train -  rows: 60000  columns: 785
Fashion MNIST test -  rows: 10000  columns: 785
(10000, 785)


# SECTION 1: Model Implementation

#Task: Model Architecture:



```
TODO: Insert an image with the Model architecture here.Replace the image Below
```
<!-- > <img src="https://miro.medium.com/v2/resize:fit:640/format:webp/1*v1ohAG82xmU6WGsG2hoE8g.png" alt="?" style="width:25px"/> -->

> <img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*2SHOuTUK51_Up3D9JMAplA.png" alt="?" style="width:25px"/>


# 1. without Regularization:
##layers:
      Conv2D layer with 32 filters
      MaxPooling2D layer
      Conv2D layer with 64 filters
      MaxPooling2D layer
      Conv2D layer with 128 filters
      Flatten layer
      Dense layer with 128 units
      Dense output layer with a number of units equal to NUM_CLASSES

# 2. With dropout Regularization:
## layers:
      Conv2D layer with 32 filters,
      MaxPooling2D layer,
      Dropout layer,
      Conv2D layer with 64 filters,
      MaxPooling2D layer,
      Dropout layer,
      Conv2D layer with 128 filters,
      Dropout layer,
      Flatten layer,
      Dense layer with 128 units,
      Dropout layer,
      Dense output layer with a number of units equal to NUM_CLASSES.

#3. With L1 Regularization:
## layers:
      Conv2D layer with 32 filters and L1 regularization
      MaxPooling2D layer
      Conv2D layer with 64 filters and L1 regularization
      MaxPooling2D layer
      Flatten layer
      Dense layer with 128 units and L1 regularization
      Dense output layer with 10 units (which corresponds to the number of classes)

#4. With L2 Regularization:
## layers:
      Conv2D layer with 32 filters, L2 regularization, ReLU activation, and he_normal kernel initializer
      MaxPooling2D layer with a 2x2 pool size
      Conv2D layer with 64 filters and L2 regularization
      MaxPooling2D layer with a 2x2 pool size
      Flatten layer to convert the 2D feature maps into a 1D vector
      Dense layer with 128 units, ReLU activation, and L2 regularization
      Dense output layer with 10 units corresponding to the number of classes, with softmax activation for classification

# Data Preprocessing

In [4]:
def data_preprocessing(raw):
    out_y = to_categorical(raw.label, NUM_CLASSES)
    num_images = raw.shape[0]
    x_as_array = raw.values[:,1:]
    x_shaped_array = x_as_array.reshape(num_images, IMG_ROWS, IMG_COLS, 1)
    out_x = x_shaped_array / 255
    return out_x, out_y

X, y = data_preprocessing(train_data)
X_test, y_test = data_preprocessing(test_data)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE)

print("Fashion MNIST train -  rows:",X_train.shape[0]," columns:", X_train.shape[1:4])
print("Fashion MNIST valid -  rows:",X_val.shape[0]," columns:", X_val.shape[1:4])
print("Fashion MNIST test -  rows:",X_test.shape[0]," columns:", X_test.shape[1:4])

Fashion MNIST train -  rows: 48000  columns: (28, 28, 1)
Fashion MNIST valid -  rows: 12000  columns: (28, 28, 1)
Fashion MNIST test -  rows: 10000  columns: (28, 28, 1)


#Task: Create A Model Without any Optimization techniques


In [25]:

model = Sequential()
# Add convolution 2D
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 kernel_initializer='he_normal',
                 input_shape=(IMG_ROWS, IMG_COLS, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64,
                 kernel_size=(3, 3),
                 activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(NUM_CLASSES, activation='softmax'))

model.compile(loss=categorical_crossentropy,
              optimizer=Adam(),
              metrics=['accuracy'])
model.save('fashion_model_mnist.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning:

You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.



In [29]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_28 (Conv2D)          (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_24 (MaxPooli  (None, 13, 13, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_29 (Conv2D)          (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_25 (MaxPooli  (None, 5, 5, 64)          0         
 ng2D)                                                           
                                                                 
 conv2d_30 (Conv2D)          (None, 3, 3, 128)         73856     
                                                                 
 flatten_13 (Flatten)        (None, 1152)            

In [28]:
# Run the model with convolutions
train_model = model.fit(X_train, y_train,
                  batch_size=BATCH_SIZE,
                  epochs=NO_EPOCHS,
                  verbose=1,
                  validation_data=(X_val, y_val))

Epoch 1/50
375/375 [==============================] - 40s 107ms/step - loss: 0.0497 - accuracy: 0.9813 - val_loss: 0.3989 - val_accuracy: 0.9101
Epoch 2/50
375/375 [==============================] - 40s 107ms/step - loss: 0.0444 - accuracy: 0.9837 - val_loss: 0.4381 - val_accuracy: 0.9068
Epoch 3/50
375/375 [==============================] - 40s 107ms/step - loss: 0.0422 - accuracy: 0.9842 - val_loss: 0.4156 - val_accuracy: 0.9099
Epoch 4/50
375/375 [==============================] - 42s 112ms/step - loss: 0.0344 - accuracy: 0.9875 - val_loss: 0.4401 - val_accuracy: 0.9103
Epoch 5/50
375/375 [==============================] - 40s 106ms/step - loss: 0.0380 - accuracy: 0.9855 - val_loss: 0.5075 - val_accuracy: 0.9053
Epoch 6/50
375/375 [==============================] - 41s 110ms/step - loss: 0.0385 - accuracy: 0.9860 - val_loss: 0.4936 - val_accuracy: 0.9087
Epoch 7/50
375/375 [==============================] - 40s 106ms/step - loss: 0.0300 - accuracy: 0.9892 - val_loss: 0.4923 - val_ac

In [34]:
# without convolution
model_2 = Sequential()

# Flatten the input image to a 1D array before feeding into Dense layers
model_2.add(Flatten(input_shape=(IMG_ROWS, IMG_COLS, 1)))
model_2.add(Dense(256, activation='relu'))
model_2.add(Dense(128, activation='relu'))
model_2.add(Dense(64, activation='relu'))
model_2.add(Dense(NUM_CLASSES, activation='softmax'))

model_2.compile(loss=categorical_crossentropy,
              optimizer=Adam(),
              metrics=['accuracy'])

model_2.save('fashion_model2_mnist.h5')

In [35]:
model_2.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_16 (Flatten)        (None, 784)               0         
                                                                 
 dense_36 (Dense)            (None, 256)               200960    
                                                                 
 dense_37 (Dense)            (None, 128)               32896     
                                                                 
 dense_38 (Dense)            (None, 64)                8256      
                                                                 
 dense_39 (Dense)            (None, 10)                650       
                                                                 
Total params: 242762 (948.29 KB)
Trainable params: 242762 (948.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [36]:
# Without Convolutions
train_model2 = model_2.fit(X_train, y_train,
                  batch_size=BATCH_SIZE,
                  epochs=NO_EPOCHS,
                  verbose=1,
                  validation_data=(X_val, y_val))

Epoch 1/50
375/375 [==============================] - 5s 9ms/step - loss: 0.5448 - accuracy: 0.8076 - val_loss: 0.4107 - val_accuracy: 0.8529
Epoch 2/50
375/375 [==============================] - 3s 7ms/step - loss: 0.3856 - accuracy: 0.8618 - val_loss: 0.3782 - val_accuracy: 0.8573
Epoch 3/50
375/375 [==============================] - 3s 7ms/step - loss: 0.3503 - accuracy: 0.8733 - val_loss: 0.3401 - val_accuracy: 0.8779
Epoch 4/50
375/375 [==============================] - 3s 9ms/step - loss: 0.3192 - accuracy: 0.8824 - val_loss: 0.3348 - val_accuracy: 0.8799
Epoch 5/50
375/375 [==============================] - 4s 11ms/step - loss: 0.3002 - accuracy: 0.8895 - val_loss: 0.3291 - val_accuracy: 0.8798
Epoch 6/50
375/375 [==============================] - 4s 11ms/step - loss: 0.2843 - accuracy: 0.8941 - val_loss: 0.3357 - val_accuracy: 0.8777
Epoch 7/50
375/375 [==============================] - 4s 12ms/step - loss: 0.2738 - accuracy: 0.8987 - val_loss: 0.3194 - val_accuracy: 0.8846
Epo

# Task: Print out the Final Model Accuracy and plot the Loss curve

### Function to plot accuracy and loss

In [41]:

def create_trace(x,y,ylabel,color):
        trace = go.Scatter(
            x = x,y = y,
            name=ylabel,
            marker=dict(color=color),
            mode = "markers+lines",
            text=x
        )
        return trace

def plot_accuracy_and_loss(train_model):
    hist = train_model.history
    acc = hist['accuracy']
    val_acc = hist['val_accuracy']
    loss = hist['loss']
    val_loss = hist['val_loss']
    epochs = list(range(1,len(acc)+1))

    trace_ta = create_trace(epochs,acc,"Training accuracy", "Green")
    trace_va = create_trace(epochs,val_acc,"Validation accuracy", "Red")
    trace_tl = create_trace(epochs,loss,"Training loss", "Blue")
    trace_vl = create_trace(epochs,val_loss,"Validation loss", "Magenta")

    fig = tools.make_subplots(rows=1,cols=2, subplot_titles=('Training and validation accuracy',
                                                             'Training and validation loss'))
    fig.append_trace(trace_ta,1,1)
    fig.append_trace(trace_va,1,1)
    fig.append_trace(trace_tl,1,2)
    fig.append_trace(trace_vl,1,2)
    fig['layout']['xaxis'].update(title = 'Epoch')
    fig['layout']['xaxis2'].update(title = 'Epoch')
    fig['layout']['yaxis'].update(title = 'Accuracy', range=[0,1])
    fig['layout']['yaxis2'].update(title = 'Loss', range=[0,1])


    iplot(fig, filename='accuracy-loss')


In [37]:
# with convolutions
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.7870286703109741
Test accuracy: 0.9114999771118164


In [38]:
# Without convolutions
score = model_2.evaluate(X_test, y_test, verbose=0)
print("Test loss: ", score[0])
print("Test accuracy: ", score[1])

Test loss:  0.525564968585968
Test accuracy:  0.896399974822998


In [43]:
# With convolutions
plot_accuracy_and_loss(train_model)

In [40]:
# Without covolutions
plot_accuracy_and_loss(train_model2)

# SECTION 2: Optimization and Regularization implementation
At this point you should now create a model that is more optimized in order to see better perfomance.
As done before make sure to plot out the loss curve and the accuracy and loss in verbose

In [44]:
#TODO:
# Model
dropout_model = Sequential()
# Add convolution 2D
dropout_model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 kernel_initializer='he_normal',
                 input_shape=(IMG_ROWS, IMG_COLS, 1)))
dropout_model.add(MaxPooling2D((2, 2)))
# Add dropouts to the model
dropout_model.add(Dropout(0.25))
dropout_model.add(Conv2D(64,
                 kernel_size=(3, 3),
                 activation='relu'))
dropout_model.add(MaxPooling2D(pool_size=(2, 2)))
# Add dropouts to the model
dropout_model.add(Dropout(0.25))
dropout_model.add(Conv2D(128, (3, 3), activation='relu'))
# Add dropouts to the model
dropout_model.add(Dropout(0.4))
dropout_model.add(Flatten())
dropout_model.add(Dense(128, activation='relu'))
# Add dropouts to the model
dropout_model.add(Dropout(0.3))
dropout_model.add(Dense(NUM_CLASSES, activation='softmax'))


dropout_model.compile(loss=categorical_crossentropy,
              optimizer=Adam(),
              metrics=['accuracy'])
dropout_model.save('trained_1_dropout_model_mnist.h5')



# Define the model with L1 regularization
model_l1 = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu',
           kernel_initializer='he_normal',
           input_shape=(28, 28, 1),
           kernel_regularizer=l1(0.01)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu',
           kernel_regularizer=l1(0.01)),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu', kernel_regularizer=l1(0.01)),
    Dense(10, activation='softmax')
])


# Define the model with L2 regularization
model_l2 = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu',
           kernel_initializer='he_normal',
           input_shape=(28, 28, 1), kernel_regularizer=l2(0.01)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu', kernel_regularizer=l2(0.01)),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(10, activation='softmax')
])


# Compile the models
model_l1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_l1.save('l1_model_mnist.h5')

model_l2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_l2.save('l2_model_mnist.h5')


In [45]:
#TODO:
dropout_train_model = dropout_model.fit(X_train, y_train,
                  batch_size=BATCH_SIZE,
                  epochs=NO_EPOCHS,
                  verbose=1,
                  validation_data=(X_val, y_val))



Epoch 1/50
375/375 [==============================] - 44s 116ms/step - loss: 0.7364 - accuracy: 0.7276 - val_loss: 0.4527 - val_accuracy: 0.8394
Epoch 2/50
375/375 [==============================] - 43s 116ms/step - loss: 0.4636 - accuracy: 0.8298 - val_loss: 0.3540 - val_accuracy: 0.8714
Epoch 3/50
375/375 [==============================] - 43s 115ms/step - loss: 0.4008 - accuracy: 0.8539 - val_loss: 0.3332 - val_accuracy: 0.8750
Epoch 4/50
375/375 [==============================] - 43s 115ms/step - loss: 0.3638 - accuracy: 0.8670 - val_loss: 0.2943 - val_accuracy: 0.8923
Epoch 5/50
375/375 [==============================] - 47s 126ms/step - loss: 0.3423 - accuracy: 0.8741 - val_loss: 0.2809 - val_accuracy: 0.8972
Epoch 6/50
375/375 [==============================] - 43s 116ms/step - loss: 0.3217 - accuracy: 0.8820 - val_loss: 0.2771 - val_accuracy: 0.9042
Epoch 7/50
375/375 [==============================] - 43s 115ms/step - loss: 0.3113 - accuracy: 0.8866 - val_loss: 0.2649 - val_ac

In [46]:
# Dropout model Loss and Accuracy
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.7870286703109741
Test accuracy: 0.9114999771118164


In [48]:
#  L1 Model training
train_model_l1 = model_l1.fit(X_train, y_train,
                  batch_size=BATCH_SIZE,
                  epochs=NO_EPOCHS,
                  verbose=1,
                  validation_data=(X_val, y_val))

Epoch 1/50
375/375 [==============================] - 39s 101ms/step - loss: 6.9454 - accuracy: 0.6173 - val_loss: 1.8423 - val_accuracy: 0.6777
Epoch 2/50
375/375 [==============================] - 34s 90ms/step - loss: 1.6183 - accuracy: 0.6881 - val_loss: 1.4369 - val_accuracy: 0.7061
Epoch 3/50
375/375 [==============================] - 35s 95ms/step - loss: 1.3866 - accuracy: 0.7009 - val_loss: 1.3262 - val_accuracy: 0.6926
Epoch 4/50
375/375 [==============================] - 34s 91ms/step - loss: 1.3075 - accuracy: 0.7109 - val_loss: 1.2722 - val_accuracy: 0.7212
Epoch 5/50
375/375 [==============================] - 36s 95ms/step - loss: 1.2837 - accuracy: 0.7126 - val_loss: 1.2711 - val_accuracy: 0.7238
Epoch 6/50
375/375 [==============================] - 37s 99ms/step - loss: 1.2651 - accuracy: 0.7156 - val_loss: 1.3303 - val_accuracy: 0.6866
Epoch 7/50
375/375 [==============================] - 35s 93ms/step - loss: 1.2523 - accuracy: 0.7181 - val_loss: 1.2611 - val_accuracy

In [49]:
# L1 Loss and accuracy
score = model_l1.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


Test loss: 1.073198676109314
Test accuracy: 0.7567999958992004


In [50]:
# L2 model training
from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

train_model_l2 = model_l2.fit(X_train, y_train,
                  batch_size=BATCH_SIZE,
                  epochs=NO_EPOCHS,
                  verbose=1,
                  validation_data=(X_val, y_val),
                              callbacks=[early_stopping])

Epoch 1/50
375/375 [==============================] - 38s 98ms/step - loss: 1.6821 - accuracy: 0.7990 - val_loss: 0.9999 - val_accuracy: 0.8295
Epoch 2/50
375/375 [==============================] - 38s 101ms/step - loss: 0.8675 - accuracy: 0.8298 - val_loss: 0.7963 - val_accuracy: 0.8061
Epoch 3/50
375/375 [==============================] - 34s 91ms/step - loss: 0.7319 - accuracy: 0.8323 - val_loss: 0.7038 - val_accuracy: 0.8322
Epoch 4/50
375/375 [==============================] - 36s 95ms/step - loss: 0.6853 - accuracy: 0.8317 - val_loss: 0.6548 - val_accuracy: 0.8447
Epoch 5/50
375/375 [==============================] - 35s 93ms/step - loss: 0.6539 - accuracy: 0.8360 - val_loss: 0.6538 - val_accuracy: 0.8298
Epoch 6/50
375/375 [==============================] - 36s 95ms/step - loss: 0.6376 - accuracy: 0.8377 - val_loss: 0.6298 - val_accuracy: 0.8415
Epoch 7/50
375/375 [==============================] - 37s 98ms/step - loss: 0.6242 - accuracy: 0.8400 - val_loss: 0.6191 - val_accuracy

In [51]:
score = model_l2.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.5054097175598145
Test accuracy: 0.8616999983787537


#Task: Make Predictions using the best saved model


Create a confusion Matrix and F1 score for both Models. Ensure outputs for the cells are visible

Finally, Make predictions using the best model. By the time you get to this cell you may realise at some point you needed to save the model so that you cal load it later

In [57]:
def make_predictions(model_path):

    # Load the model
    models = load_model(model_path)

    # Make predictions
    predictions = models.predict(X_test)
    # Convert probabilities to binary labels (0 or 1)
    # Convert predictions and true labels from one-hot encoded vectors to class labels
    predictions_labels = np.argmax(predictions, axis=1)
    true_labels = np.argmax(y_test, axis=1)

    # # Calculate the confusion matrix
    conf_matrix = confusion_matrix(true_labels, predictions_labels)
    print("Confusion Matrix:\n", conf_matrix)

    # Calculate classification report
    report = classification_report(true_labels, predictions_labels)
    # print("Classification Report:\n", report)

    # return predictions

#Modify the code appropriately

In [56]:
model_path = '/content/fashion_model_mnist.h5'
make_predictions(model_path)

313/313 [==============================] - 3s 8ms/step
Confusion Matrix:
 [[  0  33  59   0 174   0 713   3  18   0]
 [  0   0 113   0 134   0 663  38  52   0]
 [  0  10  18   0 909   0  60   1   2   0]
 [  0  11 110   0  62   0 589  15 213   0]
 [  0  10  72   0 802   0 113   2   1   0]
 [  2  34 139   6 551   0  35 219  14   0]
 [  0  12  63   0 677   0 235   4   9   0]
 [  0  56  94   0 531   0  15 303   1   0]
 [  0   9  68   0 903   0  15   1   3   1]
 [  0   5 575   0  75   0  11 315  19   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00      1000
           1       0.00      0.00      0.00      1000
           2       0.01      0.02      0.02      1000
           3       0.00      0.00      0.00      1000
           4       0.17      0.80      0.28      1000
           5       0.00      0.00      0.00      1000
           6       0.10      0.23      0.14      1000
           7       0.34      0.30     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [58]:
model_path = '/content/trained_1_dropout_model_mnist.h5'
make_predictions(model_path)

313/313 [==============================] - 5s 15ms/step
Confusion Matrix:
 [[  0   1   0   4   0  10   1   9   4 971]
 [  0   0   0   0   0   3  31   1   0 965]
 [  1   6   0   1   0  10  10  29   7 936]
 [  0   0   0   0   0   6  47   0   1 946]
 [  0   0   0   0   0   5   5   2   0 988]
 [  6   1   0   1   0  59   0   4  34 895]
 [  1   1   0   2   0  17  14  15   3 947]
 [  0   0   0   0   0   2   0   0   0 998]
 [  0   2   0   0   0  30  11   1   1 955]
 [  0   0   0   0   0   1   0   2   0 997]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [59]:
model_path = '/content/l1_model_mnist.h5'
make_predictions(model_path)

313/313 [==============================] - 2s 7ms/step
Confusion Matrix:
 [[  0  15   0   0   4   0   0 981   0   0]
 [  0  10   0   0   1   0   0 989   0   0]
 [  0   4   0   0   7   0   0 988   0   1]
 [  0   9   0   0   2   0   0 989   0   0]
 [  0   1   0   0   1   0   0 998   0   0]
 [  0   0   0   0  21   0   0 902   1  76]
 [  0   1   0   0  12   0   0 987   0   0]
 [  0   0   0   1   5   0   0 974   0  20]
 [  0   3   0   0  17   0   0 980   0   0]
 [  0   0   0   0   0   0   0 996   0   4]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [60]:
model_path = '/content/l2_model_mnist.h5'
make_predictions(model_path)

313/313 [==============================] - 4s 11ms/step
Confusion Matrix:
 [[  0   0   0 964   0  21   1   4  10   0]
 [  0   0   0 562   0 434   0   0   4   0]
 [  0   0   0 953   0   1  25   9  11   1]
 [  0   0   0 824   0 162   0   1  12   1]
 [  0   0   0 986   0   7   1   2   4   0]
 [  0   0   0 185   0 393   0  16 403   3]
 [  0   0   0 964   0   7  11   6  12   0]
 [  0   0   0 324   0  52   1   0 623   0]
 [  0   0   0 862   0  28   1   3 101   5]
 [  0   0   0 497   0 496   0   0   7   0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



Congratulations!!
